# Generated by Django 5.2.7 on 2025-11-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamentos',
            fields=[
                ('id_apartamento', models.AutoField(primary_key=True, serialize=False)),
                ('interior', models.IntegerField(blank=True, null=True)),
                ('torre', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('n_habitaciones', models.IntegerField()),
                ('n_banos', models.IntegerField()),
                ('area_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('clasificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('deposito', models.IntegerField(blank=True, null=True)),
                ('parqueadero', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Apartamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asamblea',
            fields=[
                ('id_asamblea', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField()),
                ('lugar', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('doc_convocatoria', models.TextField(blank=True, null=True)),
                ('doc_citacion', models.TextField(blank=True, null=True)),
                ('acta_asamblea', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Asamblea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conjunto',
            fields=[
                ('id_conjunto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('n_torres', models.IntegerField()),
                ('n_apartamentos', models.IntegerField()),
                ('n_parqueaderos', models.IntegerField()),
                ('reglamento_propiedad_horizontal', models.TextField(blank=True, null=True)),
                ('estatutos', models.TextField(blank=True, null=True)),
                ('manual_convivencia', models.TextField(blank=True, null=True)),
                ('estado_financiero', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Conjunto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Delegado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cedula', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Delegado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentoMensaje',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('extension', models.CharField(max_length=10)),
                ('documento', models.TextField()),
                ('fecha_subida', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Documento_Mensaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentoPublicacion',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('extension', models.CharField(max_length=10)),
                ('documento', models.TextField()),
                ('fecha_subida', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Documento_Publicacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('asunto', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField()),
                ('conversacion', models.IntegerField()),
            ],
            options={
                'db_table': 'Mensaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Peticion',
            fields=[
                ('id_peticion', models.AutoField(primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_peticion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Peticion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id_publicacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('fecha_publicacion', models.DateTimeField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('visibilidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Publicacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=150)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_reporte', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Reporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('cantidad_personas', models.IntegerField()),
                ('duracion', models.IntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Residente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('correo', models.CharField(max_length=120, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('rol', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'Usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioMensaje',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('papel', models.CharField(blank=True, max_length=8, null=True)),
                ('destacado', models.IntegerField(blank=True, null=True)),
                ('leido', models.IntegerField(blank=True, null=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Usuario_Mensaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZonaComun',
            fields=[
                ('id_zona_comun', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('horario', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('reservacion', models.IntegerField(blank=True, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('imagen', models.TextField(blank=True, null=True)),
                ('reglamento_uso', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Zona_comun',
                'managed': False,
            },
        ),
    ]
