# Generated by Django 5.2.7 on 2025-11-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoRecuperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=255)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('intentos', models.IntegerField(default=0)),
                ('usado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Código de Recuperación',
                'verbose_name_plural': 'Códigos de Recuperación',
                'indexes': [models.Index(fields=['token', 'usado'], name='core_codigo_token_b072e4_idx'), models.Index(fields=['username', 'usado'], name='core_codigo_usernam_b7dc9d_idx')],
            },
        ),
    ]
