# Generated by Django 5.2.7 on 2025-11-30 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_conjunto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conjunto',
            options={'managed': False},
        ),
    ]
