# Generated by Django 5.2.7 on 2025-11-30 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_conjunto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conjunto',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='residente',
            options={'managed': True},
        ),
    ]
