# Generated by Django 5.2.7 on 2025-11-30 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_conjunto_options_alter_residente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residente',
            options={'managed': False},
        ),
    ]
