# Generated by Django 5.2.7 on 2025-11-30 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_residente_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserva',
        ),
        migrations.DeleteModel(
            name='ZonaComun',
        ),
    ]
