# Generated by Django 5.2.7 on 2025-11-30 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_reserva_delete_zonacomun'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentoPublicacion',
        ),
        migrations.DeleteModel(
            name='Publicacion',
        ),
    ]
