# Generated by Django 5.2.7 on 2025-12-01 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_documentopublicacion_delete_publicacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentoMensaje',
        ),
        migrations.DeleteModel(
            name='Mensaje',
        ),
        migrations.DeleteModel(
            name='Reporte',
        ),
        migrations.DeleteModel(
            name='UsuarioMensaje',
        ),
    ]
