# Generated by Django 5.2.7 on 2025-11-17 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoPublicacion',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('extension', models.CharField(max_length=10)),
                ('documento', models.TextField()),
                ('fecha_subida', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Documento_Publicacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('correo', models.CharField(max_length=120, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('rol', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id_publicacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('visibilidad', models.IntegerField(blank=True, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='forum.usuario')),
            ],
            options={
                'db_table': 'Publicacion',
            },
        ),
    ]
