# Generated by Django 5.2.7 on 2025-11-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
