# Generated by Django 5.2.7 on 2025-12-01 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_delete_documentomensaje_delete_mensaje_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoMensaje',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('extension', models.CharField(max_length=10)),
                ('documento', models.TextField()),
                ('fecha_subida', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Documento_Mensaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('asunto', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField()),
                ('conversacion', models.IntegerField()),
            ],
            options={
                'db_table': 'Mensaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=150)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_reporte', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Reporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioMensaje',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('papel', models.CharField(blank=True, max_length=8, null=True)),
                ('destacado', models.IntegerField(blank=True, null=True)),
                ('leido', models.IntegerField(blank=True, null=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('id_mensaje', models.ForeignKey(db_column='id_mensaje', null=True, on_delete=django.db.models.deletion.CASCADE, to='mensajeria.mensaje')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'db_table': 'Usuario_Mensaje',
                'managed': True,
                'unique_together': {('id_usuario', 'id_mensaje')},
            },
        ),
    ]
