# Generated by Django 5.2.7 on 2025-11-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('cantidad_personas', models.IntegerField()),
                ('duracion', models.IntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZonaComun',
            fields=[
                ('id_zona_comun', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('horario', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('reservacion', models.IntegerField(blank=True, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('imagen', models.TextField(blank=True, null=True)),
                ('reglamento_uso', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Zona_comun',
                'managed': False,
            },
        ),
    ]
